name: Daily Playwright Tests

on:
  workflow_dispatch:
  schedule:
    - cron: "30 10 * * *" # Runs at 04:00 PM IST everyday

  pull_request:
    branches: [main, master]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install playwright browser
        run: npx playwright install --with-deps

      - name: Run Playwright all tests
        run: npx playwright test ./tests

      - name: Run Playwright core test
        run: npx playwright test ./core

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
